mnws/mnws/urls.py
from django.contrib import admin
from django.conf.urls import url, include
from wpb import views
from wpb.views import HomePageView
from django.contrib import admin


urlpatterns = [
    url(r'^$',HomePageView.as_view(), name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^wpb/', include('wpb.urls')),

]

mnws/wpb/urls.py
from django.conf.urls import url, include
from wpb import views
from .views import HomePageView, SearchResultsView
app_name = 'wpb'

urlpatterns = [
    url(r'^politics/$',views.politics,name='politics'),
    url(r'^politics/cts/',views.cts,name='cts'),
    url(r'^index/$',views.index,name='index'),
    url(r'^contactus/$', views.contactus, name='contactus'),
    url(r'^about/$', views.about, name='about'),
    url(r'^search/$', SearchResultsView.as_view(), name='search'),
    url(r'^search/politics/cts/',views.cts,name='cts'),
    url(r'^psych/$',views.psych,name='psych'),
    url(r'^thil/$',views.thil,name='thil'),


]

mnws/wpb/models.py
from django.db import models
class Entry(models.Model):

    title=models.CharField(max_length=255)
    link=models.CharField(max_length=255)
    class Meta:
      verbose_name_plural = "entries"
    def __str__(self):
        return self.link

mnws/wpb/views.py
from django.shortcuts import render

def index(request):
    return render(request,'wpb/index.html')
def politics(request):
    return render(request,'wpb/politics.html')
def cts(request):
    return render(request,'wpb/cts.html')
# Create your views here.
def contactus(request):
    return render(request, 'wpb/contactus.html')
def about(request):
    return render(request, 'wpb/about.html')
def psych(request):
    return render(request,'wpb/psych.html')
def thil(request):
    return render(request,'wpb/thil.html')
import re

from django.db.models import Q
from wpb.models import Entry
from django.views.generic import TemplateView, ListView



class HomePageView(TemplateView):
    template_name = 'wpb/index.html'

class SearchResultsView(ListView):
    model = Entry
    template_name = 'wpb/search.html'


    def get_queryset(self): # новый
        query = self.request.GET.get('q')
        object_list = Entry.objects.filter(
            Q(title__icontains=query) | Q(link__icontains=query)
        )
        return object_list

mnws/templates/wpb/about.html
<!DOCTYPE html>
{% extends "wpb/base.html" %}
    {% block body_block%}
    <body style="font-family:Palatino Linotype">

    <div class="container">
      <div class="jumbotron">
        <h1>О проекте</h1>
        <p>Проект был создан из интереса к теориям заговора и истории. Многие не доверяют таким теориям, однако разве из истории мало примеров того,
         как горстка людей манипулировала массами, при этом оставаясь в тени? Существует много способов спрятать правду, даже если она у всех на виду. В статьях я пытаюсь по
        возможности ссылаться на официальные источники, чтобы не было впечатления, что все это мои домыслы. </p>
        <p>Здесь вы можете всерьез задуматься и заново переосмыслить вещи, которые раньше вам казались понятными или просто получить удовольствие,
         погрузившись в историю или психологию.</p>
      </div>

    </div>



  </body>

  <!-- Need to have JQuery and Javascript for DropDown Actions to work -->

  {% endblock %}

mnws/templates/wpb/base.html
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title></title>
    <!-- Latest compiled and minified CSS -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

  </head>

  <body>

  	<!-- DOCUMENTATION NAVBAR -->

  	<nav class="navbar navbar-default navbar-inverse navbar-fixed-top">

      <!-- Inside of a Container -->
    <div class="container-fluid">

      <!-- Brand and toggle get grouped for better mobile display -->
      <!-- This is the actual code that create the "hamburger icon" -->
      <!-- The data-target grabs ids to put into the icon -->
      <div class="navbar-header">
        <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">

          <!--  Code for the hamburger icon-->
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>

        <a class="navbar-brand" style="color:white;"
        href="{% url 'wpb:index' %}">
          Mycroft Conspiracy Project</a>
      </div>

      <!-- Anything inside of collapse navbar-collapse goes into the "hamburger" -->
      <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
        <ul class="nav navbar-nav">
          <li class="active"><a href="{% url 'wpb:about' %}">О проекте <span class="sr-only">(current)</span></a></li>
          <li class="active"><a href="{% url 'wpb:politics' %}">Политика<span class="sr-only">(current)</span></a></li>
          <li class="active"><a href="{% url 'wpb:psych' %}">Психология<span class="sr-only">(current)</span></a></li>

        </ul>
        <!-- SEARCH BAR -->
        <form action="{% url 'wpb:search' %}" method="get" class="navbar-form navbar-right">
          <div class="input-group">
            <input type="text" name="q" class="form-control" placeholder="Поиск">
          </div>
          <button type="submit" class="btn btn-default" name="search">Поиск</button>
        </form>


        <!-- Stuff on the Right -->

        <ul class="nav navbar-nav navbar-right">
          <li><a href="{% url 'wpb:contactus' %}">Обратная связь</a></li>
        </ul>

      </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
  </nav>


  <!-- OTHER STUFF ON THE PAGE -->




  <!-- Need to have JQuery and Javascript for DropDown Actions to work -->

  <script
  src="http://code.jquery.com/jquery-3.1.1.js"
  integrity="sha256-16cdPddA6VdVInumRGo6IbivbERE8p7CQR3HzTBuELA="
  crossorigin="anonymous"></script>  <!-- Latest compiled and minified JavaScript -->
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  <div class="container">


    <br />
    <br />
    <br />
    <body style="  height: 650px;
  position: relative;">
  {% block body_block %}

  {# Anything outside of this will be inherited if you use extend.#}
  {% endblock %}
</body>

  </div>

</br>

<div style="font-family:Palatino Linotype;position: sticky; position: -webkit-sticky;left:0;bottom:0;width:100%; top: 100%; height: 12rem;background-color:#2e2c27; border:1px dotted #003333; padding:.8em; ">
<h4 style="color:white;font-weight: bold;">Mycroft Conspiracy Project</h4>

<span style="font-size:12pt;  font-family: 'Cambria','times new roman','garamond',serif; color:white;">Достоверность информации</span></br>
<p style="font-size:10pt; line-height:10pt; font-family: 'Cambria','times roman',serif; color: white;">Проект является любительским и не носит информационный характер. Хотя автор указывает в каждой статье степень своего личного отношения к
описываемым версиям или данным, здесь отстутствуют намерения представить статьи как источники, на которые стоит ссылаться.  </p>
<span style="padding-top:10px; font-weight:bold; color:#CC0000; font-size:10pt; font-family: 'Calibri',Arial,sans-serif; "></span></br></br>
</div>

</body>
</html>

mnws/templates/wpb/contactus.html
<!DOCTYPE html>
{% extends "wpb/base.html" %}
    {% block body_block%}
    <body style="font-family:Palatino Linotype">

  <div class="container">
    <div class="jumbotron">
      <h3>Связаться со мной можно по нижеследующим контактным данным:</h3>
<ul>
  <li>Электронная почта: <a href="mailto:kamalvalikhanov@hotmail.com">kamalvalikhanov@hotmail.com</a></li>
  <li>LinkedIn: <a href="https://www.linkedin.com/in/kamal-valikhanov-815b1143/" target="_blank">https://www.linkedin.com/in/kamal-valikhanov-815b1143/</a></li>

</ul>
    </div>

  </div>

</body>



  <!-- Need to have JQuery and Javascript for DropDown Actions to work -->

  {% endblock %}

mnws/templates/wpb/index.html
<!DOCTYPE html>
{% extends "wpb/base.html" %}
    {% block body_block%}
  <div class="container">
    <div class="jumbotron">
      <h1>Добро пожаловать!</h1>
      <p>Здесь вы можете окунуться в мир теорий заговора. Здесь ваше представление о мире может измениться. Привычные вещи поменяют свой облик.
       Вы больше не увидите мир таким как раньше.</p>
    </div>

  </div>




  <!-- Need to have JQuery and Javascript for DropDown Actions to work -->

  {% endblock %}

mnws/templates/wpb/politics.html
<!DOCTYPE html>
{% extends "wpb/base.html" %}
    {% block body_block%}


    <h3>Статьи про политику</h3>
    <ul>
      <li><a href="{% url 'wpb:cts' %}">Как США развалили СССР
</a></li>
    </ul>

    {% endblock %}

mnws/templates/wpb/psych.html
<!DOCTYPE html>
{% extends "wpb/base.html" %}
    {% block body_block%}


    <h3>Статьи про психологию</h3>
    <ul>
      <li><a href="{% url 'wpb:thil' %}">Как спрятать правду среди лжи
</a></li>
    </ul>

    {% endblock %}

mnws/templates/wpb/search.html
<!DOCTYPE html>
{% extends "wpb/base.html" %}
{% block body_block%}

<h1>Результаты поиска</h1>

<ul>
  {% for entry in object_list %}
    <li>
      <a href="{{ entry.link }}">{{ entry.title }}</a>

    </li>
  {% empty %}
      <h4>Ничего не найдено.</h4>
  {% endfor %}
</ul>
{% endblock %}

mnws/templates/wpb/thil.html
<!DOCTYPE html>
{% extends "wpb/base.html" %}
    {% block body_block%}

<title>Как спрятать правду среди лжи</title>
<body style="font-family:Palatino Linotype">
<h1>Как спрятать правду среди лжи</h1>
<p>Сильные мира сего нуждаются в том, чтобы скрывать правду от масс. Правду о преступлениях, которые они творят, богатстве, которое они
скопили, реальной власти, которую они имеют. Зачем? Потому что всегда найдется куча любителей закона и правды, которые захотят с них спросить.
или хотя бы социалистов, которые хотят равного распределения доходов (взять хотя бы скандинавские страны с их 70%-ми налогами). Проблема в том,
 что правду не так то легко скрыть. Популярны слова Авраама Линкольна на этот счет: "Можно всё время дурачить некоторых, можно некоторое время дурачить всех, но нельзя всё время дурачить всех.".
 По натуре своей человеку сложно лгать. Ложь неестественна и для ее создания человеку необходимо проявлять креативность. Хранить ее тоже нелегко.
 Кто-то скажет бликому человеку, тот другому и по цепочке правда вскоре вскроется. Тогда что делать? Как скрыть правду, если она все равно рано
 или поздно выйдет?</p>
 <p>Есть три способа:</p>
 <ul>
   <li>Примешать к правде примесь чего-то невероятного</li>
   <li>Изменить правду, добавив туда выгодные тебе детали</li>
   <li>Опорочить того, кто говорит правду</li>
 </ul>
<h4>
  Примешать примесь невероятной лжи</h4>
<p>Представьте источник, описывающий правдивые события и добавляющий туда причасность НЛО. Обычный человек на этом месте перестанет читать. Он скажет,
 что раз тут такая глупость как пришельцы, то правды тут и искать не стоит. Вы скажете, что публиковать правду без примеси невероятного будут и
другие, нормальные издания, прочтя которые, люди узнают правду. Тут вступает в силу теория контролируемого урона. Люди, обладающие властью, знают,
что правда и так
раскроется, поэтому лучше первому о ней заговорить, только примешать к ней невероятную ложь. После "лживой версии" правды люди не захотят слушать другие
 версии.</p>

 <h4>Стать первоисточником "правды"</h4>
 <p>В этом способе теория контролируемого урона особенна полезна. Одно есть дать правде распространиться, тогда люди уже успеют составить мнение,
  другое есть первым дать людям свою версию. Люди поверят тебе как первоисточнику. Часть людей позже все равно поверит более правдивым версиям,
 но "урон" можно будет смягчить.</p>
 <h4>Опорочить говорящего истину</h4>
 <p>Этот способ наверное все слышали часто из СМИ или в кино. Так правительства часто обвиняют простестующих в том, что они наркоманы, праздные
  и так далее. Если не дай Бог что-то из этого правда, то этих людей не многие станут слушать. Людям свойственно вешать ярлыки. Показания проститутки
по поводу убийства на суде далеко не все присяжные воспримут всерьез. Люди не пойдут за оппозицией, если за ним есть хоть какой-то грех, пусть даже
 и тот, который водится за многими из самого народа, пусть даже если правительство имеет грехи в десять раз хуже.</p>
</body>

   {% endblock %}